"""Interview sessions, attendance, rubrics, feedback and event reliability."""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision="20260827_0001"; down_revision=None; branch_labels:Sequence[str]|None=None; depends_on:Sequence[str]|None=None
session_status=postgresql.ENUM("scheduled","ready","in_progress","completed","candidate_no_show","interviewer_no_show","technical_failure","cancelled",name="interview_session_status",create_type=False)
participant_role=postgresql.ENUM("candidate","interviewer",name="participant_role",create_type=False)
readiness=postgresql.ENUM("not_ready","developing","interview_ready","strong",name="readiness_level",create_type=False)

def upgrade()->None:
    session_status.create(op.get_bind());participant_role.create(op.get_bind());readiness.create(op.get_bind())
    op.create_table("rubrics",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("domain",sa.String(80),nullable=False),sa.Column("topic",sa.String(120),nullable=False),sa.Column("experience_level",sa.String(40),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("criteria",postgresql.JSONB(),nullable=False),sa.Column("maximum_score",sa.Integer(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("domain","topic","experience_level","version",name="uq_rubric_version"),sa.CheckConstraint("maximum_score > 0",name="ck_rubric_max_score"));op.create_index("ix_rubrics_domain","rubrics",["domain"])
    op.create_table("interview_sessions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("booking_id",sa.Uuid(),nullable=False,unique=True),sa.Column("candidate_id",sa.Uuid(),nullable=False),sa.Column("interviewer_id",sa.Uuid(),nullable=False),sa.Column("rubric_id",sa.Uuid(),sa.ForeignKey("rubrics.id"),nullable=False),sa.Column("room_reference",sa.String(255),unique=True),sa.Column("scheduled_start",sa.DateTime(timezone=True),nullable=False),sa.Column("scheduled_end",sa.DateTime(timezone=True),nullable=False),sa.Column("actual_start",sa.DateTime(timezone=True)),sa.Column("actual_end",sa.DateTime(timezone=True)),sa.Column("total_duration_seconds",sa.Integer(),nullable=False),sa.Column("status",session_status,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("scheduled_start < scheduled_end",name="ck_interview_schedule"));op.create_index("ix_interview_sessions_booking_id","interview_sessions",["booking_id"]);op.create_index("ix_interview_sessions_candidate_id","interview_sessions",["candidate_id"]);op.create_index("ix_interview_sessions_interviewer_id","interview_sessions",["interviewer_id"])
    op.create_table("participant_attendance",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("session_id",sa.Uuid(),sa.ForeignKey("interview_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.Uuid(),nullable=False),sa.Column("role",participant_role,nullable=False),sa.Column("first_joined_at",sa.DateTime(timezone=True)),sa.Column("last_joined_at",sa.DateTime(timezone=True)),sa.Column("last_left_at",sa.DateTime(timezone=True)),sa.Column("connected",sa.Boolean(),nullable=False),sa.Column("reconnect_count",sa.Integer(),nullable=False),sa.Column("total_connected_seconds",sa.Integer(),nullable=False),sa.UniqueConstraint("session_id","role",name="uq_attendance_session_role"));op.create_index("ix_participant_attendance_session_id","participant_attendance",["session_id"]);op.create_index("ix_participant_attendance_user_id","participant_attendance",["user_id"])
    op.create_table("feedback_reports",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("session_id",sa.Uuid(),sa.ForeignKey("interview_sessions.id"),nullable=False,unique=True),sa.Column("interviewer_id",sa.Uuid(),nullable=False),sa.Column("criterion_scores",postgresql.JSONB(),nullable=False),sa.Column("strengths",postgresql.JSONB(),nullable=False),sa.Column("improvement_areas",postgresql.JSONB(),nullable=False),sa.Column("summary",sa.String(4000),nullable=False),sa.Column("readiness_level",readiness,nullable=False),sa.Column("total_score",sa.Integer(),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_feedback_reports_session_id","feedback_reports",["session_id"]);op.create_index("ix_feedback_reports_interviewer_id","feedback_reports",["interviewer_id"])
    op.create_table("processed_events",sa.Column("event_id",sa.Uuid(),primary_key=True),sa.Column("event_type",sa.String(128),nullable=False),sa.Column("processed_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("outbox_events",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("event_type",sa.String(128),nullable=False),sa.Column("event_version",sa.Integer(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("correlation_id",sa.String(128),nullable=False),sa.Column("payload",postgresql.JSONB(),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("publish_attempts",sa.Integer(),nullable=False),sa.Column("last_error",sa.Text()));op.create_index("ix_outbox_events_published_at","outbox_events",["published_at"])
    op.create_table("attendance_events",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("provider_event_id",sa.String(255),nullable=False,unique=True),sa.Column("session_id",sa.Uuid(),sa.ForeignKey("interview_sessions.id"),nullable=False),sa.Column("participant_id",sa.Uuid(),sa.ForeignKey("participant_attendance.id"),nullable=False),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_attendance_events_session_occurred","attendance_events",["session_id","occurred_at"])

def downgrade()->None:
    for table in ("attendance_events","outbox_events","processed_events","feedback_reports","participant_attendance","interview_sessions","rubrics"):op.drop_table(table)
    readiness.drop(op.get_bind());participant_role.drop(op.get_bind());session_status.drop(op.get_bind())
