apiVersion: v1
kind: ConfigMap
metadata:
  name: roundready-migration-secret-identifiers
  labels: {app.kubernetes.io/name: roundready-migrations, app.kubernetes.io/component: configuration, app.kubernetes.io/part-of: roundready, app.kubernetes.io/managed-by: kustomize}
data:
  SECRET_NAME_PREFIX: roundready-production
