apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
labels:
  - pairs: {roundready.io/environment: staging}
    includeSelectors: false
patches:
  - target: {version: v1, kind: ConfigMap, name: roundready-migration-secret-identifiers}
    patch: |-
      - {op: replace, path: /data/SECRET_NAME_PREFIX, value: roundready-staging}
